# Generated by Django 4.1.5 on 2023-02-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videochapter_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
    ]
