# Generated by Django 4.1.5 on 2023-01-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Member',
            new_name='user',
        ),
    ]
